# -*- coding: utf-8 -*-
"""n.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16w4xVx6y4a0SDahxP8ufpX_xjO8bgaSu
"""

# scraper.py
import requests
import pandas as pd
import time

# Base URLs from NSE
NIFTY50_URL = "https://www.nseindia.com/api/equity-stockIndices?index=NIFTY%2050"
HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    "Accept-Language": "en-US,en;q=0.9",
    "Accept-Encoding": "gzip, deflate, br",
}

def fetch_nifty50_data():
    """Scrape live NIFTY 50 stock data from NSE"""
    session = requests.Session()
    session.get("https://www.nseindia.com", headers=HEADERS)  # Required to set cookies
    time.sleep(1)

    response = session.get(NIFTY50_URL, headers=HEADERS)
    data = response.json()

    # Extract stock details
    records = []
    for item in data["data"]:
        records.append({
            "symbol": item["symbol"],
            "open": float(item.get("open", 0)),
            "dayHigh": float(item.get("dayHigh", 0)),
            "dayLow": float(item.get("dayLow", 0)),
            "lastPrice": float(item.get("lastPrice", 0))
        })

    df = pd.DataFrame(records)
    df.to_csv("nifty50_data.csv", index=False)
    print("✅ Scraped data saved to nifty50_data.csv")
    return df

if __name__ == "__main__":
    fetch_nifty50_data()



# analyzer.py
import pandas as pd

def analyze_momentum():
    """Analyze intraday momentum and print top 5 gainers/losers"""
    df = pd.read_csv("nifty50_data.csv")

    # Compute intraday change percentage
    df["change_%"] = ((df["lastPrice"] - df["open"]) / df["open"]) * 100

    # Top 5 gainers and losers
    top_gainers = df.sort_values(by="change_%", ascending=False).head(5)
    top_losers = df.sort_values(by="change_%", ascending=True).head(5)

    print("\n📈 Top 5 Gainers:")
    print(top_gainers[["symbol", "open", "lastPrice", "change_%"]].to_string(index=False))

    print("\n📉 Top 5 Losers:")
    print(top_losers[["symbol", "open", "lastPrice", "change_%"]].to_string(index=False))

if __name__ == "__main__":
    analyze_momentum()